name: Seed OpenDHC from Release ZIP (PR)
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download template ZIP from release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          # 1) Download from a *Release* named "seed-assets" (not just a git tag)
          gh release download seed-assets \
            -p "opendhc-template.zip" \
            -R "${{ github.repository }}"

          # 2) Unzip to a temp directory
          rm -rf /tmp/opendhc_zip
          mkdir -p /tmp/opendhc_zip
          unzip -q opendhc-template.zip -d /tmp/opendhc_zip

          # 3) Copy into the repo WITHOUT touching .git or this workflow file
          rsync -a /tmp/opendhc_zip/OpenDHC/ ./ \
            --exclude='.git/' \
            --exclude='.github/workflows/seed-opendhc.yml'

          # 4) Sanity check: ensure we're still in a git repo
          git rev-parse --is-inside-work-tree

          # 5) Optional: show a quick summary
          git status --porcelain=v1 || true
          ls -la .github/workflows || true

          # 6) Clean up
          rm -f opendhc-template.zip

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: seed/opendhc-template
          base: main
          title: "seed: add OpenDHC project files (Qt6 + AppImage + zsync)"
          commit-message: "seed: add OpenDHC project files"
          body: |
            This PR seeds the repository with the OpenDHC template:
            - Qt6/QML sources, batch processing, per-job progress, final report (CSV)
            - AppImage packaging via linuxdeploy + plugin-qt with zsync update info
            - CI workflow builds .AppImage + .zsync on tags and attaches to Releases
